services:
  database:
    image: postgres:16
    container_name: recipe_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: recipes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseContainerSupport
    ports:
      - "9999:9999"
    depends_on:
      - database

volumes:
  postgres_data: